-- Create roles
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_admin') THEN
    CREATE ROLE app_admin LOGIN PASSWORD 'passord123';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user LOGIN PASSWORD 'passord123';
  END IF;
END$$;

-- Set search path for roles
DO $$
DECLARE
    current_db TEXT;
BEGIN
    SELECT current_database() INTO current_db;
    IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_admin') THEN
        EXECUTE format('ALTER ROLE app_admin IN DATABASE %I SET search_path = app, public', current_db);
    END IF;
    IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN
        EXECUTE format('ALTER ROLE app_user IN DATABASE %I SET search_path = app, public', current_db);
    END IF;
END$$;

-- Create app schema
CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION app_admin;
CREATE EXTENSION IF NOT EXISTS citext;

-- Create ENUM types
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dep_status') THEN
    CREATE TYPE dep_status AS ENUM ('PLANNED','IN_PROGRESS','CANCELLED','DONE');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'delay_severity') THEN
    CREATE TYPE delay_severity AS ENUM ('INFO','MINOR','MAJOR');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fare_type') THEN
    CREATE TYPE fare_type AS ENUM ('ADULT','STUDENT','SENIOR');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ticket_state') THEN
    CREATE TYPE ticket_state AS ENUM ('NEW','USED','REFUNDED');
  END IF;
END$$;

-- role table
CREATE TABLE IF NOT EXISTS app.role (
  id           SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         TEXT NOT NULL UNIQUE CHECK (code ~ '^[A-Z_]+$'),
  description  TEXT
);

-- user table
CREATE TABLE IF NOT EXISTS app."user" (
  id             BIGSERIAL PRIMARY KEY,
  email          CITEXT NOT NULL UNIQUE,
  password_hash  TEXT NOT NULL,
  session_token  TEXT UNIQUE,
  full_name      TEXT NOT NULL,
  is_active      BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- user_role table
CREATE TABLE IF NOT EXISTS app.user_role (
  user_id     BIGINT    NOT NULL REFERENCES app."user"(id) ON DELETE CASCADE,
  role_id     SMALLINT  NOT NULL REFERENCES app.role(id)   ON DELETE RESTRICT,
  granted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role_id)
);

-- route table
CREATE TABLE IF NOT EXISTS app.route (
  id     BIGSERIAL PRIMARY KEY,
  code   TEXT NOT NULL UNIQUE,
  name   TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true
);

-- stop table
CREATE TABLE IF NOT EXISTS app.stop (
  id           BIGSERIAL PRIMARY KEY,
  name         TEXT NOT NULL,
  municipality TEXT,
  lat          NUMERIC(9,6) CHECK (lat BETWEEN -90 AND 90),
  lon          NUMERIC(9,6) CHECK (lon BETWEEN -180 AND 180),
  active       BOOLEAN NOT NULL DEFAULT true
);

-- route_stop table
CREATE TABLE IF NOT EXISTS app.route_stop (
  route_id      BIGINT   NOT NULL REFERENCES app.route(id) ON DELETE CASCADE,
  stop_id       BIGINT   NOT NULL REFERENCES app.stop(id)  ON DELETE RESTRICT,
  stop_sequence INTEGER  NOT NULL CHECK (stop_sequence > 0),
  dwell_time    INTERVAL,
  PRIMARY KEY (route_id, stop_id),
  UNIQUE (route_id, stop_sequence)
);

-- departure table
CREATE TABLE IF NOT EXISTS app.departure (
  id             BIGSERIAL PRIMARY KEY,
  route_id       BIGINT NOT NULL REFERENCES app.route(id) ON DELETE RESTRICT,
  planned_start  TIMESTAMPTZ NOT NULL,
  planned_end    TIMESTAMPTZ,
  vehicle_no     TEXT,
  status         dep_status NOT NULL DEFAULT 'PLANNED'
);

-- delay table
CREATE TABLE IF NOT EXISTS app.delay (
  id            BIGSERIAL PRIMARY KEY,
  departure_id  BIGINT NOT NULL REFERENCES app.departure(id) ON DELETE CASCADE,
  reported_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  delay_minutes INTEGER NOT NULL,
  reason        TEXT,
  severity      delay_severity NOT NULL,
  reported_by   BIGINT REFERENCES app."user"(id) ON DELETE SET NULL
);

-- ticket table
CREATE TABLE IF NOT EXISTS app.ticket (
  id            BIGSERIAL PRIMARY KEY,
  user_id       BIGINT NOT NULL REFERENCES app."user"(id)       ON DELETE RESTRICT,
  departure_id  BIGINT NOT NULL REFERENCES app.departure(id)     ON DELETE RESTRICT,
  qr_code_hash  TEXT NOT NULL UNIQUE,
  purchased_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  fare          fare_type NOT NULL,
  price_cents   INTEGER   NOT NULL CHECK (price_cents >= 0),
  state         ticket_state NOT NULL DEFAULT 'NEW'
);

-- Indexes
CREATE INDEX IF NOT EXISTS ix_user_role__role_id          ON app.user_role(role_id);
CREATE INDEX IF NOT EXISTS ix_route_stop__stop_id         ON app.route_stop(stop_id);
CREATE INDEX IF NOT EXISTS ix_departure__route_start      ON app.departure(route_id, planned_start);
CREATE INDEX IF NOT EXISTS ix_delay__dep_reported         ON app.delay(departure_id, reported_at DESC);
CREATE INDEX IF NOT EXISTS ix_ticket__user_purchased      ON app.ticket(user_id, purchased_at DESC);

-- Grants
GRANT USAGE ON SCHEMA app TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT
  SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT
  USAGE, SELECT ON SEQUENCES TO app_user;

-- Seed roles
INSERT INTO app.role (code, description) VALUES
  ('ADMIN','Administrator'), ('EMP','Ansatt'), ('USER','Vanlig bruker'), ('DEV','Utvikler'),
  ('ADMINISTRATOR','Administrator'), ('ANSATT','Ansatt'), ('VANLIG_BRUKER','Vanlig bruker'), ('UTVIKLER','Utvikler')
ON CONFLICT (code) DO NOTHING;

-- Seed demo user
INSERT INTO app."user"(email, password_hash, full_name)
VALUES ('demo@example.com', 'bcrypt$placeholder', 'Demo Bruker')
ON CONFLICT (email) DO NOTHING;

INSERT INTO app.user_role(user_id, role_id)
SELECT u.id, r.id
FROM app."user" u JOIN app.role r ON r.code='USER'
WHERE u.email='demo@example.com'
ON CONFLICT DO NOTHING;

-- Seed test routes and stops
INSERT INTO app.route(code, name) VALUES ('633','Skjeberg–Halden')
ON CONFLICT (code) DO NOTHING;

INSERT INTO app.stop(name, municipality, lat, lon) VALUES
  ('Sarpsborg Bussterminal','Sarpsborg', 59.283000, 11.109000),
  ('Remmen Høgskole','Halden',          59.119000, 11.387000)
ON CONFLICT DO NOTHING;

WITH rid AS (SELECT id FROM app.route WHERE code='633' LIMIT 1),
     s1  AS (SELECT id FROM app.stop WHERE name='Sarpsborg Bussterminal'),
     s2  AS (SELECT id FROM app.stop WHERE name='Remmen Høgskole')
INSERT INTO app.route_stop(route_id, stop_id, stop_sequence)
SELECT (SELECT id FROM rid), (SELECT id FROM s1), 1
ON CONFLICT DO NOTHING;

WITH rid AS (SELECT id FROM app.route WHERE code='633' LIMIT 1),
     s2  AS (SELECT id FROM app.stop WHERE name='Remmen Høgskole')
INSERT INTO app.route_stop(route_id, stop_id, stop_sequence)
SELECT (SELECT id FROM rid), (SELECT id FROM s2), 2
ON CONFLICT DO NOTHING;

INSERT INTO app.departure(route_id, planned_start, planned_end, status)
SELECT r.id, date_trunc('minute', now()) + interval '30 min',
           date_trunc('minute', now()) + interval '70 min', 'PLANNED'
FROM app.route r WHERE r.code='633'
ON CONFLICT DO NOTHING;

INSERT INTO app.ticket(user_id, departure_id, qr_code_hash, fare, price_cents)
SELECT u.id, d.id, 'qr_demo_hash', 'ADULT', 4500
FROM app."user" u
CROSS JOIN LATERAL (SELECT id FROM app.departure ORDER BY id DESC LIMIT 1) d
WHERE u.email='demo@example.com'
ON CONFLICT DO NOTHING;

-- Create transit schema
CREATE SCHEMA IF NOT EXISTS transit;
SET search_path TO transit, public;

-- Create transit ENUM types
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'service_day') THEN
    CREATE TYPE service_day AS ENUM ('WKD','SAT','SUN');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'direction') THEN
    CREATE TYPE direction AS ENUM ('OUTBOUND','INBOUND');
  END IF;
END$$;

-- line table
CREATE TABLE IF NOT EXISTS transit.line (
  id           SERIAL PRIMARY KEY,
  number       TEXT UNIQUE NOT NULL,
  name         TEXT NOT NULL,
  active_from  DATE DEFAULT DATE '2025-08-18',
  active_to    DATE DEFAULT DATE '2026-06-21'
);

-- transit.stop table
CREATE TABLE IF NOT EXISTS transit.stop (
  id     SERIAL PRIMARY KEY,
  name   TEXT NOT NULL UNIQUE,
  lat    NUMERIC(9,6),
  lon    NUMERIC(9,6)
);

-- line_stop table
CREATE TABLE IF NOT EXISTS transit.line_stop (
  line_id     INT NOT NULL REFERENCES transit.line(id) ON DELETE CASCADE,
  direction   direction NOT NULL,
  seq         INT NOT NULL,
  stop_id     INT NOT NULL REFERENCES transit.stop(id) ON DELETE RESTRICT,
  CONSTRAINT line_stop_pk PRIMARY KEY (line_id, direction, seq)
);

-- trip table
CREATE TABLE IF NOT EXISTS transit.trip (
  id          SERIAL PRIMARY KEY,
  line_id     INT NOT NULL REFERENCES transit.line(id) ON DELETE CASCADE,
  direction   direction NOT NULL,
  service     service_day NOT NULL,
  headsign    TEXT,
  notes       TEXT
);

-- stop_time table
CREATE TABLE IF NOT EXISTS transit.stop_time (
  trip_id     INT NOT NULL REFERENCES transit.trip(id) ON DELETE CASCADE,
  stop_id     INT NOT NULL REFERENCES transit.stop(id) ON DELETE RESTRICT,
  seq         INT NOT NULL,
  arrival     TIME NOT NULL,
  departure   TIME NOT NULL,
  CONSTRAINT stop_time_pk PRIMARY KEY (trip_id, stop_id)
);

-- Transit indexes
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE c.relkind='i' AND c.relname='idx_line_number' AND n.nspname='transit'
  ) THEN
    CREATE INDEX idx_line_number ON transit.line(number);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE c.relkind='i' AND c.relname='idx_stop_name' AND n.nspname='transit'
  ) THEN
    CREATE INDEX idx_stop_name ON transit.stop(name);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE c.relkind='i' AND c.relname='idx_trip_line' AND n.nspname='transit'
  ) THEN
    CREATE INDEX idx_trip_line ON transit.trip(line_id, service, direction);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE c.relkind='i' AND c.relname='idx_stop_time_trip_seq' AND n.nspname='transit'
  ) THEN
    CREATE INDEX idx_stop_time_trip_seq ON transit.stop_time(trip_id, seq);
  END IF;
END$$;

-- Transit constraints
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'stop_time_trip_seq_uniq'
  ) THEN
    ALTER TABLE transit.stop_time
      ADD CONSTRAINT stop_time_trip_seq_uniq UNIQUE (trip_id, seq);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'line_stop_unique_stop_per_dir'
  ) THEN
    ALTER TABLE transit.line_stop
      ADD CONSTRAINT line_stop_unique_stop_per_dir UNIQUE (line_id, direction, stop_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'line_stop_seq_pos'
  ) THEN
    ALTER TABLE transit.line_stop
      ADD CONSTRAINT line_stop_seq_pos CHECK (seq > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'stop_time_seq_pos'
  ) THEN
    ALTER TABLE transit.stop_time
      ADD CONSTRAINT stop_time_seq_pos CHECK (seq > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'stop_time_time_order'
  ) THEN
    ALTER TABLE transit.stop_time
      ADD CONSTRAINT stop_time_time_order CHECK (departure >= arrival);
  END IF;
END$$;

-- Transit view
CREATE OR REPLACE VIEW transit.vw_rutetider AS
SELECT 
  l.number AS linje_nr,
  l.name   AS linje_navn,
  t.id     AS trip_id,
  t.service,
  t.direction,
  s.name   AS stopp,
  st.arrival,
  st.departure,
  st.seq
FROM transit.line l
JOIN transit.trip t       ON t.line_id = l.id
JOIN transit.stop_time st ON st.trip_id = t.id
JOIN transit.stop s       ON s.id = st.stop_id
ORDER BY l.number, t.id, st.seq;

SET search_path TO app, public;

-- Grant transit access
GRANT USAGE ON SCHEMA transit TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA transit TO app_user;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA transit TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA transit GRANT
  SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA transit GRANT
  SELECT ON SEQUENCES TO app_user;

-- Seed test users (password: passord123)
INSERT INTO app."user" (email, password_hash, full_name, is_active) 
VALUES 
  ('anna@test.no', '$2a$10$N9qo8uLOickgx2ZMRZoMye1J0JrJzX5a1Dz1lHAkE0YPJ1jTN7P4K', 'Anna Hansen', true),
  ('per@test.no', '$2a$10$N9qo8uLOickgx2ZMRZoMye1J0JrJzX5a1Dz1lHAkE0YPJ1jTN7P4K', 'Per Olsen', true),
  ('admin@test.no', '$2a$10$N9qo8uLOickgx2ZMRZoMye1J0JrJzX5a1Dz1lHAkE0YPJ1jTN7P4K', 'Admin Bruker', true),
  ('julian@test.no', '$2a$10$N9qo8uLOickgx2ZMRZoMye1J0JrJzX5a1Dz1lHAkE0YPJ1jTN7P4K', 'Julian Utvikler', true)
ON CONFLICT (email) DO NOTHING;

INSERT INTO app.user_role (user_id, role_id)
SELECT u.id, r.id 
FROM app."user" u, app.role r 
WHERE (u.email = 'anna@test.no' AND r.code = 'VANLIG_BRUKER')
   OR (u.email = 'per@test.no' AND r.code = 'ANSATT')
   OR (u.email = 'admin@test.no' AND r.code = 'ADMINISTRATOR')
   OR (u.email = 'julian@test.no' AND r.code = 'UTVIKLER')
ON CONFLICT DO NOTHING;
